Algoritmo "exercício 11"
Var
   produto, valorA, valorB: real

Inicio
     escreval("============================")
     escreval("    SOMA DE DOIS VALORES    ")
     escreval("============================")

     escreva("Digite um Valor: ")
     leia(valorA)
     escreva("Digite outro Valor: ")
     leia(valorB)
     
     produto <- valorA + valorB
     escreva("A soma de ",valorA, " + ",valorB, " resulta em ",produto)

Fimalgoritmo