Algoritmo "exercício 16"
Var
   novoSalario, salarioAtual: real

Inicio
     escreval("===============================")
     escreval(" CALCULAR SALARIO COM AUMENTO  ")
     escreval("===============================")

     escreva("Qual o salario atual: ")
     leia(salarioAtual)
     
     novoSalario <- salarioAtual + ( salarioAtual * (8/100))
     escreva("Preço do produto com aumento ficou por ", novoSalario)

Fimalgoritmo