Algoritmo "exercício03"
Var
   quadrado, raiz, valor: real
   
Inicio
     escreval("============================")
     escreval(" CALCULAR RAIZ E O QUADRADO")
     escreval("============================")
     escreva("Digite o valor :")
     leia(valor)
     quadrado <- valor ^2
     escreval(valor, " ao quadrado é ",quadrado)
     raiz <- valor ^ (1/2)
     escreval(" A raiz de ",valor, " é ",raiz)

Fimalgoritmo